
{{- if contains $.Values.buildScope "cloud" }}

apiVersion: v1
kind: Service
metadata:
  name: cloud-storage-service
  labels:
    app: cloud-storage
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: cloud-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage
  labels:
     app: cloud-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-storage
  template:
    metadata:
      labels:
        app: cloud-storage
    spec:
      securityContext:
        fsGroup: {{ $.Values.groupId }}
      enableServiceLinks: false
      containers:
        - name: cloud-storage
{{- if (len $.Values.connector.cloudHost) }}
          image: {{ $.Values.registryPrefix }}smtc_storage_manager_tunnelled:latest
{{- else }}
          image: {{ $.Values.registryPrefix }}smtc_storage_manager:latest
{{- end }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: {{ printf "http://%s-service:9200" (include "smtc.db.name" .) | quote }}
            - name: PROXYHOST
              value: "http://cloud-storage-service.default.svc.cluster.local:8080"
            - name: INDEXES
              value: "recordings"
            - name: RETENTION_TIME
              value: "7200"
            - name: SERVICE_INTERVAL
              value: "3600"
            - name: WARN_DISK
              value: "75"
            - name: FATAL_DISK
              value: "85"
            - name: HALT_REC
              value: "95"
            - name: THUMBNAIL_CACHE
              value: "50"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
{{- if (len $.Values.connector.cloudHost) }}
            - name: REVERSE_TUNNEL1
              value: "{{ $.Values.connector.cloudHost }}:{{ $.Values.connector.cloudStoragePort }} cloud-storage-service:8080"
{{- end }}
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
{{- if (len $.Values.connector.cloudHost) }}
            - mountPath: /etc/hostkey
              name: hostkey
              readOnly: true
{{- end }}
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
            type: File
{{- if (len $.Values.connector.cloudHost) }}
        - name: hostkey
          secret:
            secretName: tunnel-secret
            defaultMode: 0440
{{- end }}
      {{ include "smtc.platform.node-selector" . }}

{{- end }}
