
{{- range $scenarioIdx, $scenarioName := $.Values.scenario }}
{{- $args := dict "scenarioName" $scenarioName "Values" $.Values }}
{{- range $officeIdx := until ( int ( include "smtc.noffices" $args ) ) }}
{{- $officeName := printf "%s-office%d" $scenarioName (add $officeIdx 1) }}
{{- $scope1 := printf "office%d-svc" (add $officeIdx 1) }}
{{- if contains $.Values.buildScope $scope1 }}
{{- $officeIdx2 := add (mul $officeIdx (len $.Values.scenario)) $scenarioIdx }}

{{- $args := dict "Values" $.Values }}
{{- $cameraGateway := include "smtc.cameraGateway" $args }}

{{- if eq $cameraGateway "enable" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $officeName }}-streaming-service
  labels:
    app: {{ $officeName }}-streaming
spec:
  ports:
    - port: 1935
      protocol: TCP
      targetPort: 1935
      name: rtmp
  selector:
    app: {{ $officeName }}-streaming

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $officeName }}-streaming
  labels:
     app: {{ $officeName }}-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $officeName }}-streaming
  template:
    metadata:
      labels:
        app: {{ $officeName }}-streaming
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: {{ $.Values.groupId }}
      containers:
        - name: {{ $officeName }}-streaming
          image: {{ $.Values.registryPrefix }}smtc_streaming:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1935 
          env:
            - name: OFFICE
              {{- $args := dict "scenarioName" $scenarioName "Values" $.Values "officeIdx" $officeIdx }}
              value: {{ include "smtc.env.office" $args | quote }}
            - name: DBHOST
              {{- $args := dict "officeName" $officeName "Values" $.Values }}
              value: {{ include "smtc.env.dbhost" $args | quote }}
            - name: SERVICE_INTERVAL
              value: "30"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
            - mountPath: /var/www/video
              name: video-archive
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
            type: File
        - name: video-archive
          emptyDir:
            medium: Memory
            sizeLimit: 150Mi
      {{ include "smtc.platform.node-selector" $ }}

{{- end }}
---

{{- end }}
{{- end }}
{{- end }}
