
{{- range $scenarioIdx, $scenarioName := $.Values.scenario }}
{{- $args := dict "scenarioName" $scenarioName "Values" $.Values }}
{{- range $officeIdx := until ( int ( include "smtc.noffices" $args ) ) }}
{{- $officeName := printf "%s-office%d" $scenarioName (add $officeIdx 1) }}
{{- if contains $.Values.buildScope $officeName }}
{{- $officeIdx2 := add (mul $officeIdx (len $.Values.scenario)) $scenarioIdx }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $officeName }}-storage-service
  labels:
    app: {{ $officeName }}-storage
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: {{ $officeName }}-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $officeName }}-storage
  labels:
     app: {{ $officeName }}-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $officeName }}-storage
  template:
    metadata:
      labels:
        app: {{ $officeName }}-storage
    spec:
      securityContext:
        fsGroup: {{ $.Values.groupId }}
      enableServiceLinks: false
      containers:
        - name: {{ $officeName }}-storage
{{- if (len $.Values.connector.cloudHost) }}
          image: {{ $.Values.registryPrefix }}smtc_storage_manager_tunnelled:latest
{{- else }}
          image: {{ $.Values.registryPrefix }}smtc_storage_manager:latest
{{- end }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OFFICE
              {{- $args := dict "scenarioName" $scenarioName "Values" $.Values "officeIdx" $officeIdx }}
              value: {{ include "smtc.env.office" $args | quote }}
            - name: DBHOST
              {{- $args := dict "officeName" $officeName "Values" $.Values }}
              value: {{ include "smtc.env.dbhost" $args | quote }}
            - name: INDEXES
              value: "recordings,analytics"
            - name: RETENTION_TIME
              value: "3600"
            - name: SERVICE_INTERVAL
              value: "1800"
            - name: WARN_DISK
              value: "75"
            - name: FATAL_DISK
              value: "85"
            - name: HALT_REC
              value: "95"
            - name: THUMBNAIL_CACHE
              value: "50"
{{- if (len $.Values.connector.cloudHost) }}
            - name: REVERSE_TUNNEL1
              value: "{{ $.Values.connector.cloudHost }}:{{ add $.Values.connector.officeStoragePort $officeIdx2 }} localhost:8080"
{{- end }}
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
{{- if (len $.Values.connector.cloudHost) }}
            - mountPath: /etc/hostkey
              name: hostkey
              readOnly: true
{{- end }}
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
            type: File
{{- if (len $.Values.connector.cloudHost) }}
        - name: hostkey
          secret:
            secretName: tunnel-secret
            defaultMode: 0440
{{- end }}
      {{ include "smtc.platform.node-selector" $ }}

{{- end }}
---

{{- end }}
{{- end }}
